# Generated by Django 4.1.6 on 2023-02-12 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_rename_category_article_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
