# Generated by Django 4.1.6 on 2023-02-12 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_rename_category_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
