# Generated by Django 4.1.6 on 2023-02-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_rename_categories_category_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
